artifact_location: /home/getalp/karmouah/Bureau/TutoMLflow/tracking_multiple/tracking_data_1/0
creation_time: 1719574667287
experiment_id: '0'
last_update_time: 1719574667287
lifecycle_stage: active
name: Default
