version: '3.7'
services:
  new_postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: mlflowdb1
    ports:
      - "5433:5432"
    volumes:
      - ./solo1-postgres-data:/var/lib/postgresql/data
