artifact_location: /home/getalp/karmouah/Bureau/TutoMLflow/tracking_multiple/tracking_data_2/0
creation_time: 1719923025093
experiment_id: '0'
last_update_time: 1719923025093
lifecycle_stage: active
name: Default
